name: GitHub Classroom Workflow
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          python -m venv python_venv
          source python_venv/bin/activate
          pip install conan
          conan profile detect --force
          conan install . --output-folder=. --build=missing

      - name: Build
        run: |
          cd build
          cmake .. --preset conan-release
          cd Release
          make

      - name: Run Unit Tests
        run: | 
          ./build/Release/lab_rsoi1_tests

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build And Push image
        env: 
          REF_NAME: ${{ github.ref_name }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          IMAGE_ID=ghcr.io/$GITHUB_REPOSITORY
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=v.$COMMIT_SHA
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker build -t $IMAGE_ID:$VERSION .
          docker push $IMAGE_ID:$VERSION

      - name: Deploy
        #if: github.ref_name == 'master'
        env:
          deploy_url: ${{ secrets.DEPLOY_HOOK }}
        run: |
          curl "$deploy_url"

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true
