name: GitHub Classroom Workflow
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          python -m venv python_venv
          source python_venv/bin/activate
          pip install conan
          conan profile detect --force
          conan install . --output-folder=. --build=missing

      - name: Build
        run: |
          cd build
          cmake .. --preset conan-release
          cd Release
          make
          ./lab_rsoi1

      - name: Run Unit Tests
        run: | 
          ./build/Release/lab_rsoi1_tests

      # TODO deploy project

      # - name: Run API Tests
      #   uses: matt-ball/newman-action@master
      #   with:
      #     collection: postman/[inst] Lab1.postman_collection.json
      #     environment: postman/[inst][heroku] Lab1.postman_environment.json
      #     delayRequest: 100
      #     reporters: '[ "cli" ]'

      # - name: Autograding
      #   uses: education/autograding@v1
      #   continue-on-error: true

      # - name: Github auto grader mark
      #   uses: Romanow/google-sheet-autograder-marker@v1.0
      #   with:
      #     google_token: ${{secrets.GOOGLE_API_KEY}}
      #     sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
      #     homework_number: 1
      #     user_column: 'D'
      #     column_offset: 'F'
      #     mark: "'+"